name: remote ssh command
on: [push]

env:
  FOO: "BAR"
  BAR: "FOO"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using ssh key
      uses: ./
      with:
        host: painel.bolsadedados.com.br
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: whoami