name: remote ssh command
on: [ push ]

#jobs:
#
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v1
#
#      - name: executing remote ssh commands using password
#        uses: ./
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          port: ${{ secrets.PORT }}
#          script: mkdir abc
env:
  FIRST_NAME: Mona
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.KEY}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"
